application: dnd-zgz
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static/

- url: /web/
  static_dir: web/

- url: /cache/
  static_dir: cache/
  expiration: '4d 5h'

- url: /.*
  script: main.app
